---
abstract: 'Creates a minimal local mirror of JSAN for offline installation'
author:
  - 'Adam Kennedy <adamk@cpan.org>, L<http://ali.as/>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  File::Spec: 0.80
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: JSAN::Mini
name: JSAN-Mini
no_index:
  directory:
    - inc
    - t
requires:
  JSAN::Client: 0.21
  perl: 5.6.0
resources:
  ChangeLog: http://fisheye2.atlassian.com/changelog/cpan/trunk/JSAN-Mini
  license: http://dev.perl.org/licenses/
  repository: http://svn.ali.as/cpan/trunk/JSAN-Mini
version: 1.04
